/**
 * InternLocate - Complete Tamil Nadu Industrial & Internship Database
 * Covers all 38 Districts of Tamil Nadu across all key industry sectors.
 * Each entry includes exact postal addresses, landmarks, pincodes, and map search links.
 */

const TN_DISTRICTS = [
    "Ariyalur",
    "Chengalpattu",
    "Chennai",
    "Coimbatore",
    "Cuddalore",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Kallakurichi",
    "Kancheepuram",
    "Kanniyakumari",
    "Karur",
    "Krishnagiri",
    "Madurai",
    "Mayiladuthurai",
    "Nagapattinam",
    "Namakkal",
    "Nilgiris",
    "Perambalur",
    "Pudukkottai",
    "Ramanathapuram",
    "Ranipet",
    "Salem",
    "Sivaganga",
    "Tenkasi",
    "Thanjavur",
    "Theni",
    "Thoothukudi",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tirupathur",
    "Tiruppur",
    "Tiruvallur",
    "Tiruvannamalai",
    "Tiruvarur",
    "Vellore",
    "Viluppuram",
    "Virudhunagar"
];

const TN_SECTORS = [
    "IT / Software & Cloud",
    "Automobile & Manufacturing",
    "Electronics & Embedded Systems",
    "Civil & Infrastructure",
    "Textile & Apparel",
    "Healthcare & Pharmaceuticals",
    "Banking & FinTech",
    "Agriculture & Food Processing",
    "Renewable Energy & Power",
    "Logistics & Supply Chain"
];

const ALL_COMPANIES_DATA = [
    // 1. CHENNAI (Metro IT, Cloud, FinTech, Auto)
    {
        id: "chn-01",
        name: "Apex Global Cloud Technologies",
        district: "Chennai",
        sector: "IT / Software & Cloud",
        role: "Cloud & Full Stack Intern",
        stipend: "₹12,000 / Month",
        duration: "3 Months",
        workMode: "Hybrid",
        exactAddress: "Module 403, 4th Floor, Tidel Park, No. 4, Rajiv Gandhi Salai (OMR), Taramani, Chennai, Tamil Nadu - 600113",
        landmark: "Next to Thiruvanmiyur MRTS Station",
        pincode: "600113",
        phone: "+91 44 2254 0100",
        email: "internships@apexcloudtech.in",
        website: "https://www.tidelpark.com",
        rating: 4.8,
        trainees: "140+",
        description: "Leading enterprise cloud provider offering hands-on training in AWS, Python microservices, and React web engineering.",
        skillsRequired: "Python, JavaScript, AWS Basics, SQL",
        image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80"
    },
    {
        id: "chn-02",
        name: "Hyundai Heavy Industrial Engineering",
        district: "Chennai",
        sector: "Automobile & Manufacturing",
        role: "Automotive CAD & Production Intern",
        stipend: "₹10,000 / Month",
        duration: "6 Months",
        workMode: "On-site",
        exactAddress: "Plot No. H-1, SIPCOT Industrial Park, Irungattukottai, Sriperumbudur-Chennai Corridor, Tamil Nadu - 602105",
        landmark: "Opposite Hyundai Motor Main Gate 2",
        pincode: "602105",
        phone: "+91 44 4710 5000",
        email: "campus.talent@hyundaitrain.org",
        website: "https://www.hyundai.com/in",
        rating: 4.9,
        trainees: "220+",
        description: "Automotive assembly and automated robotic chassis welding in-plant training for mechanical and production students.",
        skillsRequired: "AutoCAD, SolidWorks, Production Planning, Quality Control",
        image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=900&q=80"
    },
    {
        id: "chn-03",
        name: "Zoho Financial Systems Lab",
        district: "Chennai",
        sector: "Banking & FinTech",
        role: "FinTech Systems & Backend Trainee",
        stipend: "₹15,000 / Month",
        duration: "3 Months",
        workMode: "On-site",
        exactAddress: "Estancia IT Park, Block A, Vallancherry, GST Road, Guduvanchery, Chennai, Tamil Nadu - 603202",
        landmark: "Near SRM University Kattankulathur Campus",
        pincode: "603202",
        phone: "+91 44 6744 7000",
        email: "careers-intern@zohofin.com",
        website: "https://www.zoho.com",
        rating: 4.9,
        trainees: "180+",
        description: "FinTech gateway, automated transaction clearing, and high-concurrency Java microservice development.",
        skillsRequired: "Java, Spring Boot, PostgreSQL, REST APIs",
        image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=900&q=80"
    },
    {
        id: "chn-01",
        name: "Tata Consultancy Services (TCS)",
        district: "Chennai",
        sector: "IT / Software / Consulting",
        role: "Software Development Intern",
        stipend: "₹15,000 / Month",
        duration: "3 Months",
        workMode: "Hybrid / On-site",
        exactAddress: "Ozone Techno Park, No. 1/13, Old Mahabalipuram Road, Navallur, Chennai - 603103",
        landmark: "OMR / Navallur",
        pincode: "603103",
        phone: "Not publicly specified",
        email: "Not publicly specified",
        website: "https://www.tcs.com",
        rating: 4.5,
        trainees: "Not specified",
        description: "Global IT services and consulting company offering opportunities across software engineering, cloud, data, AI and digital technologies.",
        skillsRequired: "Java, Python, SQL, Data Structures, Problem Solving",
        image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80"
    },

    {
        id: "chn-02",
        name: "Cognizant Technology Solutions",
        district: "Chennai",
        sector: "IT / Software / Digital",
        role: "Software Engineering Intern",
        stipend: "₹15,000 / Month",
        duration: "3 Months",
        workMode: "Hybrid / On-site",
        exactAddress: "Cognizant DLF Campus, DLF IT Park, Ramapuram, Chennai - 600089",
        landmark: "DLF IT Park",
        pincode: "600089",
        phone: "1800 208 6999",
        email: "inquiry@cognizant.com",
        website: "https://www.cognizant.com",
        rating: 4.4,
        trainees: "Not specified",
        description: "Technology and consulting company working across digital engineering, cloud, data, AI and enterprise technologies.",
        skillsRequired: "Java, Python, SQL, JavaScript, Data Structures",
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=900&q=80"
    },

    {
        id: "chn-03",
        name: "Zoho Corporation",
        district: "Chennai",
        sector: "IT / Software / SaaS",
        role: "Software Development Intern",
        stipend: "₹15,000 / Month",
        duration: "3 Months",
        workMode: "On-site / Hybrid",
        exactAddress: "Estancia IT Park, Plot No. 140, 151, GST Road, Vallancheri, Chennai region",
        landmark: "Estancia IT Park",
        pincode: "603202",
        phone: "Not publicly specified",
        email: "Not publicly specified",
        website: "https://www.zoho.com",
        rating: 4.6,
        trainees: "Not specified",
        description: "SaaS company developing business software across CRM, finance, analytics, collaboration and developer platforms.",
        skillsRequired: "Java, C, C++, Python, SQL, Problem Solving",
        image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80"
    },

    {
        id: "chn-04",
        name: "Freshworks",
        district: "Chennai",
        sector: "IT / SaaS / AI",
        role: "Software Engineering Intern",
        stipend: "₹15,000 / Month",
        duration: "3 Months",
        workMode: "Hybrid",
        exactAddress: "Freshworks India Office, Chennai, Tamil Nadu",
        landmark: "Chennai IT Corridor",
        pincode: "Not specified",
        phone: "Not publicly specified",
        email: "Not publicly specified",
        website: "https://www.freshworks.com",
        rating: 4.5,
        trainees: "Not specified",
        description: "AI-first software company developing customer and employee experience products.",
        skillsRequired: "JavaScript, React, Java, Python, SQL, REST APIs",
        image: "https://images.unsplash.com/photo-1497366412874-3415097a27e7?auto=format&fit=crop&w=900&q=80"
    },

    {
        id: "chn-05",
        name: "Wipro",
        district: "Chennai",
        sector: "IT / Software / Consulting",
        role: "Software Engineering Intern",
        stipend: "₹15,000 / Month",
        duration: "3 Months",
        workMode: "Hybrid / On-site",
        exactAddress: "Chennai Development Center, 475A, Old Mahabalipuram Road, Sholinganallur, Chennai - 600119",
        landmark: "Sholinganallur OMR",
        pincode: "600119",
        phone: "+91 44 24500200",
        email: "Not publicly specified",
        website: "https://www.wipro.com",
        rating: 4.3,
        trainees: "Not specified",
        description: "Global technology services company working in cloud, software engineering, cybersecurity, data and digital transformation.",
        skillsRequired: "Java, Python, SQL, JavaScript, Cloud Basics",
        image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80"
    },

    {
        id: "chn-06",
        name: "HCLTech",
        district: "Chennai",
        sector: "IT / Software / Engineering",
        role: "Software Development Intern",
        stipend: "₹15,000 / Month",
        duration: "3 Months",
        workMode: "Hybrid / On-site",
        exactAddress: "HCLTech ELCOT-SEZ, Sholinganallur, Chennai - 600119",
        landmark: "ELCOT SEZ",
        pincode: "600119",
        phone: "Not publicly specified",
        email: "Not publicly specified",
        website: "https://www.hcltech.com",
        rating: 4.3,
        trainees: "Not specified",
        description: "Technology company providing engineering, cloud, cybersecurity, software and digital transformation services.",
        skillsRequired: "Java, Python, C++, SQL, Cloud Computing",
        image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80"
    },

    {
        id: "chn-07",
        name: "Infosys",
        district: "Chennai",
        sector: "IT / Software / Consulting",
        role: "Technology Intern",
        stipend: "₹15,000 / Month",
        duration: "3 Months",
        workMode: "Hybrid / On-site",
        exactAddress: "138, Old Mahabalipuram Road, Sholinganallur, Chennai - 600119",
        landmark: "OMR Sholinganallur",
        pincode: "600119",
        phone: "+91 44 6927 3500",
        email: "Not publicly specified",
        website: "https://www.infosys.com",
        rating: 4.4,
        trainees: "Not specified",
        description: "Global digital services and consulting company working across cloud, AI, data, software engineering and enterprise technologies.",
        skillsRequired: "Java, Python, SQL, Data Structures, Cloud Basics",
        image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80"
    },

    {
        id: "chn-08",
        name: "Accenture",
        district: "Chennai",
        sector: "IT / Consulting / AI",
        role: "Technology Intern",
        stipend: "₹15,000 / Month",
        duration: "3 Months",
        workMode: "Hybrid",
        exactAddress: "Accenture Chennai Offices, Tamil Nadu",
        landmark: "Chennai IT Corridor",
        pincode: "Not specified",
        phone: "Not publicly specified",
        email: "Not publicly specified",
        website: "https://www.accenture.com",
        rating: 4.4,
        trainees: "Not specified",
        description: "Technology and consulting company working across AI, analytics, cloud, cybersecurity, software and digital engineering.",
        skillsRequired: "Python, Java, SQL, Cloud, AI/ML Basics",
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=900&q=80"
    },

    {
        id: "chn-09",
        name: "Capgemini",
        district: "Chennai",
        sector: "IT / Consulting / Engineering",
        role: "Software Engineering Intern",
        stipend: "₹15,000 / Month",
        duration: "3 Months",
        workMode: "Hybrid",
        exactAddress: "Capgemini Chennai Offices, SIPCOT / OMR region, Chennai",
        landmark: "Chennai IT Corridor",
        pincode: "Not specified",
        phone: "Not publicly specified",
        email: "Not publicly specified",
        website: "https://www.capgemini.com",
        rating: 4.3,
        trainees: "Not specified",
        description: "Technology and consulting company with Chennai operations spanning financial services, engineering and digital technologies.",
        skillsRequired: "Java, Python, SQL, JavaScript, Cloud Basics",
        image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80"
    },

    {
        id: "chn-10",
        name: "Tech Mahindra",
        district: "Chennai",
        sector: "IT / Software / Digital",
        role: "Software / Data Engineering Intern",
        stipend: "₹15,000 / Month",
        duration: "3 Months",
        workMode: "Hybrid",
        exactAddress: "Tech Mahindra Chennai ELCOT / Sholinganallur region",
        landmark: "ELCOT SEZ",
        pincode: "600119",
        phone: "Not publicly specified",
        email: "Not publicly specified",
        website: "https://www.techmahindra.com",
        rating: 4.2,
        trainees: "Not specified",
        description: "Digital transformation and technology services company with Chennai operations in software, data, cloud and enterprise systems.",
        skillsRequired: "Python, SQL, Java, Cloud, Data Engineering",
        image: "https://images.unsplash.com/photo-1497366412874-3415097a27e7?auto=format&fit=crop&w=900&q=80"
    },

    {
        id: "chn-11",
        name: "LTIMindtree",
        district: "Chennai",
        sector: "IT / Software / Digital",
        role: "Software Development Intern",
        stipend: "₹15,000 / Month",
        duration: "3 Months",
        workMode: "Hybrid",
        exactAddress: "LTIMindtree Chennai Offices, Tamil Nadu",
        landmark: "Chennai IT Corridor",
        pincode: "Not specified",
        phone: "Not publicly specified",
        email: "Not publicly specified",
        website: "https://www.ltimindtree.com",
        rating: 4.2,
        trainees: "Not specified",
        description: "Technology consulting and digital solutions company working across cloud, data, enterprise applications and software engineering.",
        skillsRequired: "Java, Python, SQL, JavaScript, Data Structures",
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=900&q=80"
    },

    {
        id: "chn-12",
        name: "Ford Business Solutions",
        district: "Chennai",
        sector: "Automotive Technology / IT",
        role: "Software / Data Analytics Intern",
        stipend: "₹15,000 / Month",
        duration: "3 Months",
        workMode: "Hybrid",
        exactAddress: "Ford Chennai Technology / Business Operations, Tamil Nadu",
        landmark: "Chennai IT Corridor",
        pincode: "Not specified",
        phone: "Not publicly specified",
        email: "Not publicly specified",
        website: "https://www.ford.com",
        rating: 4.3,
        trainees: "Not specified",
        description: "Automotive technology and business operations organization with engineering, software, analytics and digital technology functions.",
        skillsRequired: "Python, SQL, Data Analytics, Java, Cloud Basics",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=80"
    },

    {
        id: "chn-13",
        name: "Deloitte",
        district: "Chennai",
        sector: "Consulting / IT / Analytics",
        role: "Technology / Analytics Intern",
        stipend: "₹15,000 / Month",
        duration: "3 Months",
        workMode: "Hybrid",
        exactAddress: "Deloitte Chennai Offices, Tamil Nadu",
        landmark: "Chennai IT Corridor",
        pincode: "Not specified",
        phone: "Not publicly specified",
        email: "Not publicly specified",
        website: "https://www.deloitte.com",
        rating: 4.3,
        trainees: "Not specified",
        description: "Professional services organization with technology, analytics, cybersecurity, consulting and digital transformation roles.",
        skillsRequired: "Python, SQL, Excel, Data Analytics, Communication",
        image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80"
    },

    {
        id: "chn-14",
        name: "Virtusa",
        district: "Chennai",
        sector: "IT / Digital Engineering",
        role: "Software Engineering Intern",
        stipend: "₹15,000 / Month",
        duration: "3 Months",
        workMode: "Hybrid",
        exactAddress: "Virtusa Chennai Office, Tamil Nadu",
        landmark: "Chennai IT Corridor",
        pincode: "Not specified",
        phone: "Not publicly specified",
        email: "Not publicly specified",
        website: "https://www.virtusa.com",
        rating: 4.1,
        trainees: "Not specified",
        description: "Digital engineering and IT services company working on cloud, software development, data and enterprise platforms.",
        skillsRequired: "Java, Python, SQL, React, REST APIs",
        image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80"
    },

    {
        id: "chn-15",
        name: "CitiusTech",
        district: "Chennai",
        sector: "Healthcare Technology / IT",
        role: "Software Engineering Intern",
        stipend: "₹15,000 / Month",
        duration: "3 Months",
        workMode: "Hybrid",
        exactAddress: "CitiusTech Chennai Office, Tamil Nadu",
        landmark: "Chennai IT Corridor",
        pincode: "Not specified",
        phone: "Not publicly specified",
        email: "Not publicly specified",
        website: "https://www.citiustech.com",
        rating: 4.2,
        trainees: "Not specified",
        description: "Healthcare technology company working on software engineering, data analytics, cloud and healthcare platforms.",
        skillsRequired: "Java, Python, SQL, Data Structures, React",
        image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80"
    },


    // 2. COIMBATORE (Robotics, Engineering, Textile Machinery, IT)
    {
        id: "cbe-01",
        name: "Kovai Robotics & Embedded Automation",
        district: "Coimbatore",
        sector: "Electronics & Embedded Systems",
        role: "Embedded Systems & IoT Trainee",
        stipend: "₹8,500 / Month",
        duration: "2 Months",
        workMode: "On-site",
        exactAddress: "ELCOT IT SEZ, Block B, TIDEL Park Coimbatore, Vilankurichi Road, Civil Aerodrome Post, Coimbatore, Tamil Nadu - 641014",
        landmark: "Opposite Codissia Trade Fair Complex",
        pincode: "641014",
        phone: "+91 422 251 3400",
        email: "interns@kovairobotics.com",
        website: "https://www.elcot.in",
        rating: 4.7,
        trainees: "115+",
        description: "Industrial IoT node design, STM32 microcontrollers, CAN-bus integration, and PCB fabrication.",
        skillsRequired: "Embedded C, Arduino/ESP32, Microcontrollers, Circuit Design",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80"
    },
    {
        id: "cbe-02",
        name: "LMW Precision Textile Automation",
        district: "Coimbatore",
        sector: "Textile & Apparel",
        role: "Textile Machinery & Automation Intern",
        stipend: "₹9,000 / Month",
        duration: "1-2 Weeks In-Plant",
        workMode: "On-site",
        exactAddress: "Periyanaickenpalayam Industrial Estate, Mettupalayam Road, Coimbatore, Tamil Nadu - 641020",
        landmark: "Near LMW Unit 1 Railway Crossing",
        pincode: "641020",
        phone: "+91 422 269 2371",
        email: "training@lmwtextile.co.in",
        website: "https://www.lmwglobal.com",
        rating: 4.8,
        trainees: "190+",
        description: "Advanced spinning machinery mechanics, automated yarn sensor calibration, and industrial pneumatics.",
        skillsRequired: "Industrial Automation, PLC Basics, Mechanical Maintenance",
        image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=900&q=80"
    },

    // 3. CHENGALPATTU (Automotive Hub & IT Corridors)
    {
        id: "cpt-01",
        name: "Mahindra World City Precision Auto Parts",
        district: "Chengalpattu",
        sector: "Automobile & Manufacturing",
        role: "Vehicle Testing & Quality Assurance Intern",
        stipend: "₹11,000 / Month",
        duration: "3 Months",
        workMode: "On-site",
        exactAddress: "Plot No. TP 2/1, 2nd Cross Road, Mahindra World City, Paranur, Chengalpattu District, Tamil Nadu - 603004",
        landmark: "Opposite Paranur Railway Station",
        pincode: "603004",
        phone: "+91 44 3747 4000",
        email: "hr.intern@mwcauto.com",
        website: "https://www.mahindraworldcity.com",
        rating: 4.8,
        trainees: "130+",
        description: "Vehicle chassis durability testing, electric powertrain quality audits, and ISO automotive standards.",
        skillsRequired: "Mechanical QA, CATIA, GD&T, Technical Reporting",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=80"
    },

    // 4. MADURAI (IT & Precision Foundry)
    {
        id: "mdu-01",
        name: "TVS Mobility & Logistics Tech Center",
        district: "Madurai",
        sector: "Logistics & Supply Chain",
        role: "Supply Chain & ERP Systems Trainee",
        stipend: "₹10,500 / Month",
        duration: "3 Months",
        workMode: "Hybrid",
        exactAddress: "7B, West Veli Street, Near Periyar Bus Stand, Madurai, Tamil Nadu - 625001",
        landmark: "Adjacent to Madurai Junction Railway Complex",
        pincode: "625001",
        phone: "+91 452 234 4411",
        email: "campus@tvsmobility.in",
        website: "https://www.tvsmobility.com",
        rating: 4.7,
        trainees: "95+",
        description: "State-of-the-art fleet telematics, freight warehouse ERP systems, and predictive demand tracking.",
        skillsRequired: "Supply Chain Basics, Python/Excel Data Modeling, SQL",
        image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=900&q=80"
    },
    {
        id: "mdu-02",
        name: "Madurai ELCOT IT Hub (HCL Tech Campus)",
        district: "Madurai",
        sector: "IT / Software & Cloud",
        role: "Associate Software Engineer Intern",
        stipend: "₹12,000 / Month",
        duration: "6 Months",
        workMode: "Hybrid",
        exactAddress: "ELCOT Special Economic Zone, Ilandhaikulam Ring Road, Madurai, Tamil Nadu - 625020",
        landmark: "Near Pandi Kovil Junction",
        pincode: "625020",
        phone: "+91 452 660 3000",
        email: "mdu.internships@hcltechcampus.in",
        website: "https://www.hcltech.com",
        rating: 4.8,
        trainees: "160+",
        description: "Full stack web architectures, data warehousing, and automated unit testing for global clients.",
        skillsRequired: "JavaScript, React, Node.js, Git, Problem Solving",
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=900&q=80"
    },

    // 5. TIRUCHIRAPPALLI (BHEL, Heavy Engineering, Civil)
    {
        id: "try-01",
        name: "Trichy Heavy Boiler & Pressure Vessels Unit",
        district: "Tiruchirappalli",
        sector: "Automobile & Manufacturing",
        role: "Thermal & Pressure Vessel Fabrication Intern",
        stipend: "₹9,500 / Month",
        duration: "1-2 Weeks In-Plant",
        workMode: "On-site",
        exactAddress: "Industrial Area Complex, BHEL Township Post, Kailasapuram, Trichy, Tamil Nadu - 620014",
        landmark: "Near BHEL Gate No. 5",
        pincode: "620014",
        phone: "+91 431 257 7000",
        email: "training.bheltrichy@bhel.in",
        website: "https://www.bhel.com",
        rating: 4.9,
        trainees: "250+",
        description: "Supercritical boiler tubes welding, non-destructive testing (NDT), metallurgy, and stress calculations.",
        skillsRequired: "Thermodynamics, Welding Tech, NDT Basics, Industrial Safety",
        image: "https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=80"
    },
    {
        id: "try-02",
        name: "Cauvery Infrastructure & Civil Builders",
        district: "Tiruchirappalli",
        sector: "Civil & Infrastructure",
        role: "Structural Estimation & Site Engineer Intern",
        stipend: "₹8,000 / Month",
        duration: "3 Months",
        workMode: "On-site",
        exactAddress: "No. 45, Thillai Nagar 11th Cross East, Tiruchirappalli, Tamil Nadu - 620018",
        landmark: "Behind Shastri Towers",
        pincode: "620018",
        phone: "+91 431 276 1122",
        email: "sitecareers@cauveryinfra.com",
        website: "https://www.trichyinfra.org",
        rating: 4.6,
        trainees: "80+",
        description: "Reinforced concrete design, site soil testing, highway leveling, and total station surveying.",
        skillsRequired: "AutoCAD Civil 3D, Quantity Surveying, Site Supervision",
        image: "https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?auto=format&fit=crop&w=900&q=80"
    },

    // 6. SALEM (Steel, Metallurgy, Sago & Power)
    {
        id: "slm-01",
        name: "Salem Special Steel Plant (SAIL)",
        district: "Salem",
        sector: "Automobile & Manufacturing",
        role: "Stainless Steel Rolling & Metallurgy Intern",
        stipend: "₹9,000 / Month",
        duration: "1-2 Weeks In-Plant",
        workMode: "On-site",
        exactAddress: "Salem Steel Plant Complex, Mohan Nagar Post, Salem, Tamil Nadu - 636030",
        landmark: "Near Salem Steel Plant Main Hospital Gate",
        pincode: "636030",
        phone: "+91 427 238 2441",
        email: "trainees.sail@salemsteel.co.in",
        website: "https://www.sail.co.in",
        rating: 4.8,
        trainees: "210+",
        description: "Cold and hot rolling mills, stainless steel alloy metallurgy, and blast furnace automated telemetry.",
        skillsRequired: "Metallurgy, Material Science, Industrial Instrumentation",
        image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=900&q=80"
    },
    {
        id: "slm-02",
        name: "Yercaud Agro & Food Processing Labs",
        district: "Salem",
        sector: "Agriculture & Food Processing",
        role: "Food Quality & Packaging Tech Intern",
        stipend: "₹7,500 / Month",
        duration: "2 Months",
        workMode: "On-site",
        exactAddress: "Plot No. 18, SIDCO Industrial Estate, Five Roads, Meyyanur, Salem, Tamil Nadu - 636004",
        landmark: "Near New Bus Stand Salem",
        pincode: "636004",
        phone: "+91 427 244 8899",
        email: "lab.intern@yercaudagro.in",
        website: "https://www.tnagrisalem.gov.in",
        rating: 4.5,
        trainees: "70+",
        description: "Starch derivative processing, HACCP food hygiene compliance, and modified atmosphere packaging.",
        skillsRequired: "Food Microbiology, Quality Standards, Chemical Analysis",
        image: "https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=900&q=80"
    },

    // 7. TIRUPPUR (Textile & Knitwear Capital)
    {
        id: "tpr-01",
        name: "KnitCity Export Apparel Tech Hub",
        district: "Tiruppur",
        sector: "Textile & Apparel",
        role: "Garment Production & CAD Pattern Intern",
        stipend: "₹10,000 / Month",
        duration: "3 Months",
        workMode: "On-site",
        exactAddress: "TEA Complex, 60 Feet Road, Kumarananthapuram, Tiruppur, Tamil Nadu - 641602",
        landmark: "Near Tiruppur Exporters Association Building",
        pincode: "641602",
        phone: "+91 421 223 2988",
        email: "careers@knitcityapparel.com",
        website: "https://www.tiruppurexporters.com",
        rating: 4.8,
        trainees: "150+",
        description: "Automated computerized sewing, garment pattern digitizers, sustainable dyeing, and export shipping QA.",
        skillsRequired: "Textile Technology, Gerber/Optitex CAD, Quality Inspection",
        image: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=900&q=80"
    },

    // 8. ERODE (Bhavani Carpets, Turmeric & Agri-Tech)
    {
        id: "erd-01",
        name: "Erode Solar & Bio-Energy Power Grid",
        district: "Erode",
        sector: "Renewable Energy & Power",
        role: "Solar Inverter & Grid Synchronization Intern",
        stipend: "₹8,500 / Month",
        duration: "3 Months",
        workMode: "On-site",
        exactAddress: "Plot No. 44, Perundurai SIPCOT Industrial Complex, Vijayamangalam Road, Erode District, Tamil Nadu - 638052",
        landmark: "Near SIPCOT Fire Station",
        pincode: "638052",
        phone: "+91 4294 220 110",
        email: "solar.recruitment@erodepower.in",
        website: "https://www.erodepower.in",
        rating: 4.6,
        trainees: "90+",
        description: "High-capacity photovoltaic tracking systems, grid inverters, battery storage management, and high-voltage safety.",
        skillsRequired: "Electrical Machines, Power Electronics, MATLAB/Simulink",
        image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=900&q=80"
    },

    // 9. KRISHNAGIRI (Hosur Industrial Corridor, EVs & Electronics)
    {
        id: "kri-01",
        name: "Ather Energy EV Manufacturing Plant",
        district: "Krishnagiri",
        sector: "Automobile & Manufacturing",
        role: "Electric Vehicle Powertrain & BMS Intern",
        stipend: "₹14,000 / Month",
        duration: "6 Months",
        workMode: "On-site",
        exactAddress: "Plot No. 14, SIPCOT Phase 2, Industrial Complex, Hosur, Krishnagiri District, Tamil Nadu - 635109",
        landmark: "Next to Titan Precision Engineering Division",
        pincode: "635109",
        phone: "+91 4344 277 888",
        email: "ev.campus@atherenergy.com",
        website: "https://www.atherenergy.com",
        rating: 4.9,
        trainees: "175+",
        description: "Lithium-ion Battery Management Systems (BMS), high-precision robotic chassis assembly, and motor drive testing.",
        skillsRequired: "Battery Technology, Embedded C, Vehicle Dynamics, CAN Bus",
        image: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=900&q=80"
    },

    // 10. TIRUNELVELI (Wind Energy, IT & High-Tech)
    {
        id: "tnv-01",
        name: "Suzlon Wind Power & Generator Research",
        district: "Tirunelveli",
        sector: "Renewable Energy & Power",
        role: "Wind Turbine Control Systems Intern",
        stipend: "₹10,000 / Month",
        duration: "3 Months",
        workMode: "On-site",
        exactAddress: "Gangaikondan IT & Industrial Park, NH 44 Highway, Tirunelveli, Tamil Nadu - 627352",
        landmark: "Opposite Gangaikondan Substation",
        pincode: "627352",
        phone: "+91 462 248 6000",
        email: "careers.wind@suzlon-tn.com",
        website: "https://www.suzlon.com",
        rating: 4.7,
        trainees: "105+",
        description: "Wind aero-blade strain sensing, SCADA monitoring systems, and induction generator maintenance.",
        skillsRequired: "SCADA, Power Systems, Industrial Automation, Electrical Safety",
        image: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=900&q=80"
    },

    // 11. VELLORE (Leather Tech, IT, Medical Technology)
    {
        id: "vel-01",
        name: "Ranipet Tannery & Finished Products SEZ",
        district: "Vellore",
        sector: "Textile & Apparel",
        role: "Chemical Processing & Quality Inspector",
        stipend: "₹8,000 / Month",
        duration: "2 Months",
        workMode: "On-site",
        exactAddress: "Plot No. 12, SIDCO Industrial Estate, Katpadi Road, Vellore, Tamil Nadu - 632007",
        landmark: "Near Katpadi Junction",
        pincode: "632007",
        phone: "+91 416 224 3355",
        email: "interns@velloreindustrial.org",
        website: "https://www.velloresez.in",
        rating: 4.5,
        trainees: "65+",
        description: "Chrome-free eco-friendly tanning, membrane effluent filtration, and tensile quality testing.",
        skillsRequired: "Chemical Engineering Basics, Analytical Chemistry, Quality Testing",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80"
    },

    // 12. RANIPET (BHEL Boiler Auxiliary & Chemicals)
    {
        id: "rpt-01",
        name: "BAP BHEL Industrial Pollution Control Plant",
        district: "Ranipet",
        sector: "Civil & Infrastructure",
        role: "Electrostatic Precipitator Design Intern",
        stipend: "₹9,500 / Month",
        duration: "1-2 Weeks In-Plant",
        workMode: "On-site",
        exactAddress: "Boiler Auxiliaries Plant, BHEL Ranipet, Indira Nagar, Ranipet District, Tamil Nadu - 632406",
        landmark: "Near Ranipet Railway Goods Shed",
        pincode: "632406",
        phone: "+91 4172 241 170",
        email: "training.bap@bhel.in",
        website: "https://www.bhel.com",
        rating: 4.8,
        trainees: "140+",
        description: "Heavy electrostatic precipitators, desulphurization units, and industrial pollution control equipment.",
        skillsRequired: "Mechanical Drafting, Industrial Safety, Fluid Dynamics",
        image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=900&q=80"
    },

    // 13. KANCHEEPURAM (Automotive SEZ & Silk Technology)
    {
        id: "kpm-01",
        name: "Royal Enfield (Eicher Motors) Assembly Facility",
        district: "Kancheepuram",
        sector: "Automobile & Manufacturing",
        role: "Engine Assembly & Dyno Testing Intern",
        stipend: "₹11,500 / Month",
        duration: "3 Months",
        workMode: "On-site",
        exactAddress: "Plot No. G-116, SIPCOT Industrial Park, Vallam Vadagal, Sriperumbudur Taluk, Kancheepuram District, Tamil Nadu - 602105",
        landmark: "Near Vallam Toll Plaza",
        pincode: "602105",
        phone: "+91 44 4719 2000",
        email: "careers.motorcycles@eicher.in",
        website: "https://www.royalenfield.com",
        rating: 4.9,
        trainees: "200+",
        description: "Motorcycle twin-cylinder engine assembly line, dyno power curve analysis, and robotic paint application.",
        skillsRequired: "Automotive Engineering, Metrology, IC Engines, 5S Principles",
        image: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=900&q=80"
    },

    // 14. THOOTHUKUDI (Port Logistics & Chemical Plants)
    {
        id: "thk-01",
        name: "V.O. Chidambaranar Port Authority Maritime Hub",
        district: "Thoothukudi",
        sector: "Logistics & Supply Chain",
        role: "Port Operations & Freight Logistics Intern",
        stipend: "₹9,000 / Month",
        duration: "3 Months",
        workMode: "On-site",
        exactAddress: "Administrative Building, Harbour Estate, Tuticorin Port, Thoothukudi, Tamil Nadu - 628004",
        landmark: "Near Tuticorin Maritime Lighthouse",
        pincode: "628004",
        phone: "+91 461 235 2290",
        email: "vocport.training@vocport.gov.in",
        website: "https://www.vocport.gov.in",
        rating: 4.8,
        trainees: "135+",
        description: "Container terminal logistics, bulk cargo crane scheduling, maritime customs clearance, and EDI tracking.",
        skillsRequired: "Logistics ERP, Supply Chain Management, Operations Research",
        image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=900&q=80"
    },
    {
        id: "thk-02",
        name: "SPIC Heavy Petrochemicals & Fertilizers",
        district: "Thoothukudi",
        sector: "Healthcare & Pharmaceuticals",
        role: "Chemical Plant Process Control Intern",
        stipend: "₹8,500 / Month",
        duration: "1-2 Weeks In-Plant",
        workMode: "On-site",
        exactAddress: "SPIC Nagar, Muthiapuram Post, Thoothukudi, Tamil Nadu - 628005",
        landmark: "Near SPIC Main Plant Gate",
        pincode: "628005",
        phone: "+91 461 235 5555",
        email: "hrd@spic.co.in",
        website: "https://www.spic.in",
        rating: 4.6,
        trainees: "110+",
        description: "Ammonia synthesis reactors, cryogenic storage tanks, and automated PLC chemical pipeline telemetry.",
        skillsRequired: "Chemical Process Tech, Safety Engineering, Mass Transfer",
        image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=900&q=80"
    },

    // 15. CUDDALORE (NLC Neyveli & SIPCOT Chemicals)
    {
        id: "cud-01",
        name: "NLC India Limited (Lignite Power Corporation)",
        district: "Cuddalore",
        sector: "Renewable Energy & Power",
        role: "Thermal Power & Conveyor Systems Intern",
        stipend: "₹10,500 / Month",
        duration: "1-2 Weeks In-Plant",
        workMode: "On-site",
        exactAddress: "Thermal Power Station-II, Corporate Office Complex, Block 1, Neyveli, Cuddalore District, Tamil Nadu - 607801",
        landmark: "Near Central Bus Stand Neyveli Township",
        pincode: "607801",
        phone: "+91 4142 252 204",
        email: "hr.training@nlcindia.in",
        website: "https://www.nlcindia.in",
        rating: 4.9,
        trainees: "240+",
        description: "Open-cast lignite mining bucket-wheel excavators, high-speed belt conveyors, and steam turbine generators.",
        skillsRequired: "Power Plant Engineering, Electrical Distribution, Mining Machinery",
        image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=900&q=80"
    },

    // 16. THANJAVUR (Agro-Industries & Food Processing)
    {
        id: "tnj-01",
        name: "National Institute of Food Technology (NIFTEM) R&D",
        district: "Thanjavur",
        sector: "Agriculture & Food Processing",
        role: "Post-Harvest Technology & Food Tech Intern",
        stipend: "₹9,000 / Month",
        duration: "3 Months",
        workMode: "On-site",
        exactAddress: "Pudukkottai Road, NIFTEM Campus, Thanjavur, Tamil Nadu - 613005",
        landmark: "Near Thanjavur New Housing Unit",
        pincode: "613005",
        phone: "+91 4362 228 155",
        email: "training@niftem-t.ac.in",
        website: "https://www.niftem-t.ac.in",
        rating: 4.8,
        trainees: "120+",
        description: "Paddy grain silo automation, nutritional extrusion processing, and biological shelf-life extension analysis.",
        skillsRequired: "Food Engineering, Food Chemistry, Laboratory QA",
        image: "https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=900&q=80"
    },

    // 17. DINDIGUL (Lock & Brass Engineering, Leather, Agro)
    {
        id: "dgl-01",
        name: "Dindigul Precision Metallurgy & Lock Hub",
        district: "Dindigul",
        sector: "Automobile & Manufacturing",
        role: "Tool & Die Making Mechanical Intern",
        stipend: "₹8,000 / Month",
        duration: "2 Months",
        workMode: "On-site",
        exactAddress: "Plot No. 22, SIDCO Industrial Estate, Nagal Nagar, Dindigul, Tamil Nadu - 624003",
        landmark: "Opposite Nagal Nagar Railway Gate",
        pincode: "624003",
        phone: "+91 451 243 0088",
        email: "careers@dindigulmetal.in",
        website: "https://www.dindigulindustrial.org",
        rating: 4.5,
        trainees: "75+",
        description: "Brass forging, CNC wire-EDM cutting, hardened tumbler manufacturing, and electro-plating techniques.",
        skillsRequired: "CNC Programming, Tool Design, Lathe & Milling",
        image: "https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=80"
    },

    // 18. KANNIYAKUMARI (Renewable Energy, Rubber & IT)
    {
        id: "kki-01",
        name: "Cape Comorin Solar & Wind Energy Facility",
        district: "Kanniyakumari",
        sector: "Renewable Energy & Power",
        role: "Renewable Power Grid Intern",
        stipend: "₹8,500 / Month",
        duration: "3 Months",
        workMode: "On-site",
        exactAddress: "Aralvaimozhi Wind Farm Junction, NH 944, Muppandal Wind Corridor, Kanniyakumari District, Tamil Nadu - 629301",
        landmark: "Near Aralvaimozhi Pass Substation",
        pincode: "629301",
        phone: "+91 4652 261 400",
        email: "greenpower@capewindenergy.com",
        website: "https://www.teda.in",
        rating: 4.7,
        trainees: "85+",
        description: "World famous Muppandal wind corridor grid synchronization, aerodynamic pitch controls, and transmission monitoring.",
        skillsRequired: "Electrical Grid Basics, Transmission Lines, SCADA",
        image: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=900&q=80"
    },

    // 19. KARUR (Textile Home Furnishing & Bus Body Building)
    {
        id: "krr-01",
        name: "Karur Bus Body Works & Heavy Structural Fabrication",
        district: "Karur",
        sector: "Automobile & Manufacturing",
        role: "Commercial Vehicle Body Design Intern",
        stipend: "₹8,500 / Month",
        duration: "2 Months",
        workMode: "On-site",
        exactAddress: "No. 88, Gandhigramam South, Thanthonimalai Road, Karur, Tamil Nadu - 639004",
        landmark: "Behind Collectorate Office Complex",
        pincode: "639004",
        phone: "+91 4324 255 120",
        email: "info@karurbusworks.co.in",
        website: "https://www.karurbusbody.com",
        rating: 4.6,
        trainees: "90+",
        description: "Heavy coach chassis alteration, roll-over cage structural safety, fiberglass molding, and sheet metal pressing.",
        skillsRequired: "Sheet Metal CAD, Structural Welds, Automotive Regulations",
        image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=900&q=80"
    },

    // 20. NAMAKKAL (Poultry Tech & Transport Logistics)
    {
        id: "nmk-01",
        name: "Namakkal Transport Fleet & Telematics Control",
        district: "Namakkal",
        sector: "Logistics & Supply Chain",
        role: "Fleet Telematics & IoT Tracking Intern",
        stipend: "₹9,000 / Month",
        duration: "3 Months",
        workMode: "Hybrid",
        exactAddress: "Plot No. 15, Lorry Owners Association Complex, Salem Road, Namakkal, Tamil Nadu - 637001",
        landmark: "Near Namakkal Bus Stand",
        pincode: "637001",
        phone: "+91 4286 276 345",
        email: "internships@namakkaltransport.in",
        website: "https://www.namakkallorry.com",
        rating: 4.7,
        trainees: "80+",
        description: "Heavy multi-axle truck telematics, GPS cold-chain temperature sensors, route optimization algorithms.",
        skillsRequired: "GPS Telematics, Python, Excel Analytics, Logistics Tracking",
        image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=900&q=80"
    },

    // 21. NILGIRIS (Tea Processing, Bio-Pharma & Cordite Factory)
    {
        id: "nil-01",
        name: "Pasteur Institute of India (Vaccine & Bio-Pharma)",
        district: "Nilgiris",
        sector: "Healthcare & Pharmaceuticals",
        role: "Biotechnology & Vaccine Production Intern",
        stipend: "₹10,000 / Month",
        duration: "3 Months",
        workMode: "On-site",
        exactAddress: "Pasteur Institute Campus, Coonoor, The Nilgiris District, Tamil Nadu - 643103",
        landmark: "Near Sim's Park Botanical Gardens",
        pincode: "643103",
        phone: "+91 423 223 1250",
        email: "careers@pasteurinstitute.gov.in",
        website: "https://www.pasteurinstitute.gov.in",
        rating: 4.9,
        trainees: "70+",
        description: "Antirabies and DTP vaccine culturing, sterile bio-reactor operation, lyophilization, and pharmaceutical cleanroom standards.",
        skillsRequired: "Microbiology, Bio-reactors, Biochemistry, Cleanroom Protocols",
        image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=900&q=80"
    },

    // 22. VIRUDHUNAGAR (Printing, Fireworks & Food Processing)
    {
        id: "vnr-01",
        name: "Sivakasi Offset Print & Security Packaging Hub",
        district: "Virudhunagar",
        sector: "Textile & Apparel",
        role: "Automated Printing Press & Packaging Intern",
        stipend: "₹8,500 / Month",
        duration: "2 Months",
        workMode: "On-site",
        exactAddress: "No. 120, Sattur Road, Sivakasi Industrial Area, Virudhunagar District, Tamil Nadu - 626123",
        landmark: "Near Sivakasi Master Printers Association",
        pincode: "626123",
        phone: "+91 4562 220 540",
        email: "careers@sivakasiprint.org",
        website: "https://www.sivakasiprinting.com",
        rating: 4.8,
        trainees: "115+",
        description: "Eight-color Heidelberg offset printing, holographic security foil application, and automated corrugated carton forming.",
        skillsRequired: "Print Media Tech, Color Management, Mechanical Maintenance",
        image: "https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=80"
    },

    // 23. ARIYALUR (Cement & Limestone Mining)
    {
        id: "ari-01",
        name: "Dalmia Cement Bharat Works Ltd",
        district: "Ariyalur",
        sector: "Civil & Infrastructure",
        role: "Cement Chemistry & Heavy Clinker Production Intern",
        stipend: "₹9,500 / Month",
        duration: "1-2 Weeks In-Plant",
        workMode: "On-site",
        exactAddress: "Dalmiapuram Works, Ariyalur Main Road, Ariyalur District, Tamil Nadu - 621651",
        landmark: "Near Dalmiapuram Railway Station",
        pincode: "621651",
        phone: "+91 4329 235 444",
        email: "training.cement@dalmiacement.com",
        website: "https://www.dalmiacement.com",
        rating: 4.7,
        trainees: "130+",
        description: "Rotary kiln thermal efficiency, limestone chemical testing, concrete admixture analysis, and zero-emission carbon capture.",
        skillsRequired: "Chemical Testing, Civil Concrete Tech, Process Engineering",
        image: "https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?auto=format&fit=crop&w=900&q=80"
    },

    // 24. PERAMBALUR (SEZ & Agro Manufacturing)
    {
        id: "pbl-01",
        name: "MRF Tyres & Rubber Compound SEZ",
        district: "Perambalur",
        sector: "Automobile & Manufacturing",
        role: "Tire Vulcanization & Rubber Chemistry Intern",
        stipend: "₹10,000 / Month",
        duration: "3 Months",
        workMode: "On-site",
        exactAddress: "SIPCOT Industrial Complex, Eraiyur Village, Veppanthattai Taluk, Perambalur District, Tamil Nadu - 621133",
        landmark: "Near Trichy-Chennai NH 38 Toll Gate",
        pincode: "621133",
        phone: "+91 4328 290 800",
        email: "careers.era@mrftyres.com",
        website: "https://www.mrftyres.com",
        rating: 4.8,
        trainees: "140+",
        description: "Radial tire automated bead winding, curing bladder vulcanization, tensile failure analysis, and synthetic polymer testing.",
        skillsRequired: "Polymer Science, Mechanical Quality, Production Line Monitoring",
        image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=900&q=80"
    },

    // 25. PUDUKKOTTAI (Textile, Granite & Engineering)
    {
        id: "pdk-01",
        name: "Pudukkottai Precision Granite & Stone Engineering",
        district: "Pudukkottai",
        sector: "Civil & Infrastructure",
        role: "Geological Survey & CNC Stone Profiling Intern",
        stipend: "₹8,000 / Month",
        duration: "2 Months",
        workMode: "On-site",
        exactAddress: "Plot No. 19, SIPCOT Industrial Park, Mathur, Pudukkottai District, Tamil Nadu - 622515",
        landmark: "Near Mathur Roundana Trichy Road",
        pincode: "622515",
        phone: "+91 4322 271 220",
        email: "careers@pdkgranites.in",
        website: "https://www.pudukkottai.tn.gov.in",
        rating: 4.5,
        trainees: "65+",
        description: "Multi-axis bridge saw cutting, waterjet stone sculpting, geological rock core testing, and export container packing.",
        skillsRequired: "CAD Drafting, Surveying, Civil Materials",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=80"
    },

    // 26. SIVAGANGA (Karaikudi Electro-Chemical CSIR & IT)
    {
        id: "svg-01",
        name: "CSIR - Central Electrochemical Research Institute (CECRI)",
        district: "Sivaganga",
        sector: "Electronics & Embedded Systems",
        role: "Electrochemical Energy Storage & Battery Research Trainee",
        stipend: "₹11,000 / Month",
        duration: "3 Months",
        workMode: "On-site",
        exactAddress: "College Road, Karaikudi, Sivaganga District, Tamil Nadu - 630003",
        landmark: "Opposite Alagappa University Campus",
        pincode: "630003",
        phone: "+91 4565 241 400",
        email: "academic.training@cecri.res.in",
        website: "https://www.cecri.res.in",
        rating: 4.9,
        trainees: "180+",
        description: "Sodium-ion and Lithium-ion prototype battery fabrication, supercapacitor impedance spectroscopy, and solar corrosion coatings.",
        skillsRequired: "Electrochemistry, Material Characterization, Instrumentation",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80"
    },

    // 27. RAMANATHAPURAM (Solar & Marine Blue-Economy)
    {
        id: "rmd-01",
        name: "Kamuthi Mega Solar Power Complex (Adani Green)",
        district: "Ramanathapuram",
        sector: "Renewable Energy & Power",
        role: "648MW Solar Field Operations & SCADA Intern",
        stipend: "₹10,000 / Month",
        duration: "3 Months",
        workMode: "On-site",
        exactAddress: "Kamuthi Solar Plant Site, Sengapadai Road, Kamuthi Taluk, Ramanathapuram District, Tamil Nadu - 623603",
        landmark: "Near Sengapadai Solar Substation 400kV",
        pincode: "623603",
        phone: "+91 4576 292 100",
        email: "solar.kamuthi@adanigreen.com",
        website: "https://www.adanigreenenergy.com",
        rating: 4.8,
        trainees: "100+",
        description: "Hands-on experience in one of the world's largest single-location solar power plants (648 MW), automated cleaning robots and high-voltage substations.",
        skillsRequired: "Electrical Engineering, High-Voltage Safety, Solar Inverters, SCADA",
        image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=900&q=80"
    },

    // 28. TENKASI (Paper Mills, Textiles & Agri-Tech)
    {
        id: "tks-01",
        name: "Seshasayee Paper & Agro Boards Facility",
        district: "Tenkasi",
        sector: "Agriculture & Food Processing",
        role: "Cellulose Pulp & Water Recycling Trainee",
        stipend: "₹8,500 / Month",
        duration: "1-2 Weeks In-Plant",
        workMode: "On-site",
        exactAddress: "Courtallam Main Road, Tenkasi District, Tamil Nadu - 627811",
        landmark: "Near Tenkasi New Bus Terminus",
        pincode: "627811",
        phone: "+91 4633 222 710",
        email: "trainee@tenkasipaper.co.in",
        website: "https://www.tenkasi.nic.in",
        rating: 4.6,
        trainees: "75+",
        description: "Bagasse eco-friendly pulp digestion, multi-cylinder paper sheet forming, and automated effluent recycling reverse-osmosis.",
        skillsRequired: "Chemical Engineering, Environmental Science, Process Control",
        image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=900&q=80"
    },

    // 29. THENI (Textiles, Cardamom Tech & Wind Power)
    {
        id: "thn-01",
        name: "Western Ghats Organic Processing & Essential Oils",
        district: "Theni",
        sector: "Healthcare & Pharmaceuticals",
        role: "Natural Extract Chemistry & QC Intern",
        stipend: "₹8,000 / Month",
        duration: "2 Months",
        workMode: "On-site",
        exactAddress: "Plot No. 5, SIDCO Estate, Allinagaram, Theni, Tamil Nadu - 625531",
        landmark: "Opposite Theni Collectorate",
        pincode: "625531",
        phone: "+91 4546 250 330",
        email: "qc@theninaturals.in",
        website: "https://www.theni.nic.in",
        rating: 4.5,
        trainees: "60+",
        description: "Supercritical CO2 extraction of cardamom and spice oleoresins, gas chromatography mass-spectrometry (GC-MS), and organic certification.",
        skillsRequired: "Chromatography, Chemistry Lab Skills, Pharma Testing",
        image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=900&q=80"
    },

    // 30. TIRUVALLUR (Auto Hub, Heavy Vehicles & Port)
    {
        id: "tvl-01",
        name: "Ashok Leyland Heavy Commercial Vehicle Plant",
        district: "Tiruvallur",
        sector: "Automobile & Manufacturing",
        role: "Heavy Truck Transmission & Chassis Intern",
        stipend: "₹12,000 / Month",
        duration: "3 Months",
        workMode: "On-site",
        exactAddress: "Ennore Industrial Estate, Kathivakkam High Road, Ennore, Tiruvallur District, Tamil Nadu - 600057",
        landmark: "Near Ennore Railway Station",
        pincode: "600057",
        phone: "+91 44 2575 1200",
        email: "intern.ennore@ashokleyland.com",
        website: "https://www.ashokleyland.com",
        rating: 4.9,
        trainees: "210+",
        description: "Heavy-duty 9-speed manual and automated synchromesh gearboxes, pneumatic air-brake testing, and robotic cab painting.",
        skillsRequired: "Automotive Transmission, Mechanical Engineering, CAD/CAM",
        image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=900&q=80"
    },

    // 31. TIRUVANNAMALAI (Agro-Rice Mills & Power Systems)
    {
        id: "tvm-01",
        name: "Arunachala Modern Agro Silos & Biomass Energy",
        district: "Tiruvannamalai",
        sector: "Agriculture & Food Processing",
        role: "Biomass Gasifier & Automated Silo Intern",
        stipend: "₹7,500 / Month",
        duration: "2 Months",
        workMode: "On-site",
        exactAddress: "No. 34, Polur Road Industrial Area, Tiruvannamalai, Tamil Nadu - 606601",
        landmark: "Near Tiruvannamalai Railway Overbridge",
        pincode: "606601",
        phone: "+91 4175 233 400",
        email: "careers@arunachalaagro.in",
        website: "https://www.tiruvannamalai.nic.in",
        rating: 4.5,
        trainees: "70+",
        description: "High-capacity paddy sorting optical color sorters, biomass husk gasification to clean electrical power.",
        skillsRequired: "Mechanical Drives, Electrical Control Panels, Agro Machinery",
        image: "https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=900&q=80"
    },

    // 32. TIRUVARUR (Agriculture, Oil & Natural Gas)
    {
        id: "tvr-01",
        name: "ONGC Cauvery Basin Exploration Base",
        district: "Tiruvarur",
        sector: "Renewable Energy & Power",
        role: "Petroleum Reservoir & Drilling Instrumentation Intern",
        stipend: "₹11,000 / Month",
        duration: "1-2 Weeks In-Plant",
        workMode: "On-site",
        exactAddress: "ONGC Forward Base Office, Mannargudi Road, Tiruvarur, Tamil Nadu - 610001",
        landmark: "Behind Tiruvarur District Court Complex",
        pincode: "610001",
        phone: "+91 4366 222 300",
        email: "training.cauvery@ongc.co.in",
        website: "https://www.ongcindia.com",
        rating: 4.8,
        trainees: "95+",
        description: "Natural gas extraction telemetry, well-head pressure monitoring, seismic data analysis, and hazardous environment safety protocols.",
        skillsRequired: "Instrumentation, Fluid Mechanics, Petroleum Geophysics, Safety Rules",
        image: "https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=80"
    },

    // 33. NAGAPATTINAM (Port, Marine Engineering & Chemical)
    {
        id: "ngp-01",
        name: "Nagapattinam Deepwater Harbor Logistics & Maritime",
        district: "Nagapattinam",
        sector: "Logistics & Supply Chain",
        role: "Marine Vessel Navigation & Dredging Tech Intern",
        stipend: "₹8,500 / Month",
        duration: "2 Months",
        workMode: "On-site",
        exactAddress: "Port Officer Building, Beach Road, Nagapattinam Port, Tamil Nadu - 611001",
        landmark: "Near Nagapattinam Light House",
        pincode: "611001",
        phone: "+91 4365 242 220",
        email: "nagaport@tnmaritime.gov.in",
        website: "https://www.tnmaritime.com",
        rating: 4.6,
        trainees: "60+",
        description: "Coastal passenger vessel mooring, diesel auxiliary propulsion, tidal bathymetry surveying, and marine customs documentation.",
        skillsRequired: "Marine Engineering Basics, Nautical Knowledge, Port Regulations",
        image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=900&q=80"
    },

    // 34. MAYILADUTHURAI (Textiles, Handloom & Agro)
    {
        id: "myd-01",
        name: "Cauvery Delta Agri-Tech & Smart Irrigation Hub",
        district: "Mayiladuthurai",
        sector: "Agriculture & Food Processing",
        role: "Smart Irrigation & Soil Sensor Intern",
        stipend: "₹7,500 / Month",
        duration: "2 Months",
        workMode: "On-site",
        exactAddress: "No. 14, Pattamangala Street, Mayiladuthurai, Tamil Nadu - 609001",
        landmark: "Near Mayuranathar Temple South Entrance",
        pincode: "609001",
        phone: "+91 4364 227 890",
        email: "delta.interns@smartirrigate.org",
        website: "https://www.mayiladuthurai.nic.in",
        rating: 4.5,
        trainees: "55+",
        description: "IoT soil moisture probes, LoRaWAN wireless irrigation valves, delta canal telemetry, and organic nutrient dosing systems.",
        skillsRequired: "IoT Sensors, Electronics Basics, Microcontrollers",
        image: "https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=900&q=80"
    },

    // 35. DHARMAPURI (Horticulture, Electronics & Granite)
    {
        id: "dhp-01",
        name: "Dharmapuri Fruit Pulp & Tetra-Pak Processing Labs",
        district: "Dharmapuri",
        sector: "Agriculture & Food Processing",
        role: "Aseptic Fruit Processing & Automation Intern",
        stipend: "₹8,000 / Month",
        duration: "3 Months",
        workMode: "On-site",
        exactAddress: "SIPCOT Industrial Complex, Collectorate Post, Dharmapuri, Tamil Nadu - 636705",
        landmark: "Near Dharmapuri SIPCOT Substation",
        pincode: "636705",
        phone: "+91 4342 230 450",
        email: "info@dharmapuripulp.com",
        website: "https://www.dharmapuri.nic.in",
        rating: 4.6,
        trainees: "70+",
        description: "High-capacity mango and guava puree refining, continuous tubular pasteurizers, and aseptic automated pouch packaging lines.",
        skillsRequired: "Food Processing Technology, PLC Monitoring, Quality Control",
        image: "https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=900&q=80"
    },

    // 36. KALLAKURICHI (Sugar Mills & Agriculture)
    {
        id: "klk-01",
        name: "Kallakurichi Co-operative Sugar Mills & Cogeneration",
        district: "Kallakurichi",
        sector: "Renewable Energy & Power",
        role: "Boiler Cogeneration & Steam Turbine Intern",
        stipend: "₹8,000 / Month",
        duration: "1-2 Weeks In-Plant",
        workMode: "On-site",
        exactAddress: "Moongilthuraipattu, Sankarapuram Taluk, Kallakurichi District, Tamil Nadu - 605702",
        landmark: "Near Moongilthuraipattu Bus Stand",
        pincode: "605702",
        phone: "+91 4151 258 220",
        email: "sugarmills@kallakurichi.gov.in",
        website: "https://www.kallakurichi.nic.in",
        rating: 4.5,
        trainees: "65+",
        description: "Sugarcane crushing rollers, multi-effect evaporation pans, and high-pressure steam turbines feeding the state electricity grid.",
        skillsRequired: "Mechanical Engineering, Steam Turbines, Thermodynamics",
        image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=900&q=80"
    },

    // 37. VILUPPURAM (Chemicals, Footwear & Agro)
    {
        id: "vpm-01",
        name: "Viluppuram Electronic Component & Footwear SEZ",
        district: "Viluppuram",
        sector: "Electronics & Embedded Systems",
        role: "SMT Assembly Line & PCB Inspection Intern",
        stipend: "₹8,500 / Month",
        duration: "2 Months",
        workMode: "On-site",
        exactAddress: "Plot No. 8, SIDCO Industrial Estate, Trichy Main Road, Viluppuram, Tamil Nadu - 605602",
        landmark: "Behind Viluppuram Government Polytechnic",
        pincode: "605602",
        phone: "+91 4146 228 110",
        email: "careers@viluppuramind.in",
        website: "https://www.viluppuram.nic.in",
        rating: 4.6,
        trainees: "85+",
        description: "Surface Mount Technology (SMT) pick-and-place robotics, automated optical inspection (AOI) of soldering, and consumer electronic boards.",
        skillsRequired: "PCB Soldering, Electronics Hardware, SMT Operations",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80"
    },

    // 38. TIRUPATHUR (Leather Machinery, IT & Granite)
    {
        id: "tpt-01",
        name: "Ambur Modern Finished Leather & CAD Footwear Hub",
        district: "Tirupathur",
        sector: "Textile & Apparel",
        role: "Shoe CAD Modeling & Laser Cutting Intern",
        stipend: "₹9,000 / Month",
        duration: "3 Months",
        workMode: "On-site",
        exactAddress: "MC Road, Ambur Industrial Sector, Tirupathur District, Tamil Nadu - 635802",
        landmark: "Near Ambur Railway Station",
        pincode: "635802",
        phone: "+91 4174 242 660",
        email: "design.intern@amburleather.com",
        website: "https://www.tirupathur.nic.in",
        rating: 4.7,
        trainees: "90+",
        description: "High-precision CAD sole modeling, laser pattern cutter programming, stitching endurance testing for European footwear brands.",
        skillsRequired: "CAD Modeling, Material Stress Testing, Production Planning",
        image: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=900&q=80"
    }
];

// Helper to generate Google Maps Search URL for exact address
function getGoogleMapsUrl(company) {
    const query = encodeURIComponent(`${company.name}, ${company.exactAddress}`);
    return `https://www.google.com/maps/search/?api=1&query=${query}`;
}
